// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcKTrvxJDePEmCiPAES7x9jcXxcyDA4gE',
    appId: '1:46367660069:web:1c96b9e18d62124396c7cc',
    messagingSenderId: '46367660069',
    projectId: 'wishlist-app-b6f85',
    authDomain: 'wishlist-app-b6f85.firebaseapp.com',
    storageBucket: 'wishlist-app-b6f85.firebasestorage.app',
    measurementId: 'G-RZ0S3JMZWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZaxjkxSu1yxX8zzdR1AGarZFOE0H23Qg',
    appId: '1:46367660069:android:1f5c0628e5892bc596c7cc',
    messagingSenderId: '46367660069',
    projectId: 'wishlist-app-b6f85',
    storageBucket: 'wishlist-app-b6f85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSMqaTRZSsVwDVxwDKDidyaQDe7s6wIw4',
    appId: '1:46367660069:ios:fc729232c125f9ee96c7cc',
    messagingSenderId: '46367660069',
    projectId: 'wishlist-app-b6f85',
    storageBucket: 'wishlist-app-b6f85.firebasestorage.app',
    iosBundleId: 'com.example.wishList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSMqaTRZSsVwDVxwDKDidyaQDe7s6wIw4',
    appId: '1:46367660069:ios:fc729232c125f9ee96c7cc',
    messagingSenderId: '46367660069',
    projectId: 'wishlist-app-b6f85',
    storageBucket: 'wishlist-app-b6f85.firebasestorage.app',
    iosBundleId: 'com.example.wishList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcKTrvxJDePEmCiPAES7x9jcXxcyDA4gE',
    appId: '1:46367660069:web:744c7f3c2417a93096c7cc',
    messagingSenderId: '46367660069',
    projectId: 'wishlist-app-b6f85',
    authDomain: 'wishlist-app-b6f85.firebaseapp.com',
    storageBucket: 'wishlist-app-b6f85.firebasestorage.app',
    measurementId: 'G-S7HR1YW585',
  );
}
